# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - kline-riya3

on:
  push:
    branches:
      - expand-textbox-with-text
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://792d10abcb004922a8095a98f3c6b917.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5d732c08485a480ea46c7100c873b562 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5af236ec1a024dec961d968ad3056607 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: 792d10abcb004922a8095a98f3c6b917.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5d732c08485a480ea46c7100c873b562 }}/duncan-chatapp:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'kline-riya3'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_fe62d76fa24a4ad887ecbb9d9815da40 }}
        images: '792d10abcb004922a8095a98f3c6b917.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5d732c08485a480ea46c7100c873b562 }}/duncan-chatapp:${{ github.sha }}'